--offers
create table offers
(
    id           bigint not null
        primary key,
    created_by   bigint,
    offer_code   varchar(255)
        constraint ukhqyg9645547d7emihkkt0xlm9
            unique,
    place_name   varchar(255),
    product_code varchar(255)
);

alter table offers
    owner to postgres;

-- permission
create table permissions
(
    id           bigint generated by default as identity
        primary key,
    created_date timestamp(6) not null,
    name         varchar(255) not null
        constraint ukpnvtwliis6p05pn6i3ndjrqt2
            unique,
    updated_date timestamp(6) not null
);

alter table permissions
    owner to postgres;

--places
create table places
(
    id           bigint generated by default as identity
        primary key,
    created_by   bigint,
    created_date timestamp(6) not null,
    name         varchar(255) not null,
    updated_date timestamp(6) not null,
    updated_by   bigint,
    region_id    bigint       not null
        constraint fk2lkjoxuwr4yu8n2asamaimeug
            references regions
);

alter table places
    owner to postgres;

--products
create table products
(
    id             bigint       not null
        primary key,
    created_by     bigint,
    created_date   timestamp(6) not null,
    product_image  varchar(255),
    product_name   varchar(255),
    product_price numeric(38, 2),
    updated_date   timestamp(6) not null,
    updated_by     bigint
);

alter table products
    owner to postgres;

--regions
create table regions
(
    id           bigint generated by default as identity
        primary key,
    created_by   bigint,
    created_date timestamp(6) not null,
    name         varchar(255) not null
        constraint uk1m9qnhbk56c8iskxvfupln9me
            unique,
    updated_date timestamp(6) not null,
    updated_by   bigint
);

alter table regions
    owner to postgres;
-- request
create table requests
(
    id           bigint       not null
        primary key,
    created_by   bigint,
    created_date timestamp(6) not null,
    place_name   varchar(255),
    product_code varchar(255),
    request_code varchar(255)
        constraint uk8kbxp1ynoh7efu3rocqs2iks0
            unique,
    updated_date timestamp(6) not null,
    updated_by   bigint
);

alter table requests
    owner to postgres;



--roles

create table roles
(
    id           bigint generated by default as identity
        primary key,
    created_by   bigint,
    created_date timestamp(6) not null,
    role         varchar(255),
    updated_date timestamp(6) not null,
    updated_by   bigint
);

alter table roles
    owner to postgres;




--transactions
create table transactions
(
    id               bigint generated by default as identity
        primary key,
    carrier_username varchar(255) not null,
    created_at       timestamp(6) not null,
    offer_code       varchar(255) not null,
    request_code     varchar(255) not null,
    score            integer,
    transaction_code varchar(255) not null
        constraint ukhmrka43k7ijk56xcfcnscaq14
            unique
);

alter table transactions
    owner to postgres;
--users
create table users
(
    id            bigint generated by default as identity
        primary key,
    created_date  timestamp(6) not null,
    email         varchar(255),
    is_enabled    boolean,
    encoding_type varchar(255) not null,
    first_name    varchar(255),
    image         varchar(255),
    last_name     varchar(255),
    password      varchar(255),
    role          varchar(255),
    updated_date  timestamp(6) not null,
    user_name     varchar(255) not null
        constraint ukk8d0f2n7n88w1a16yhua64onx
            unique
);

alter table users
    owner to postgres;


